load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "frame_builder_by_value",
    testonly = True,
    hdrs = ["frame_builder_by_value.h"],
    deps = [
        "//src/mac:ethernet_frame",
        "//src/mac:frame_builder",
    ],
)

cc_library(
    name = "mac_test_util",
    testonly = True,
    hdrs = ["mac_test_util.h"],
    deps = ["//src/mac:mac_address"],
)

cc_test(
    name = "mac_address_test",
    srcs = ["mac_address_test.cpp"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
        "//src/mac:mac_address",
        ":mac_test_util",
    ],
    target_compatible_with = ["@pico-sdk//bazel/constraint:host"],
)

cc_test(
    name = "crc32_test",
    srcs = ["crc32_test.cpp"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
        "//src/mac:crc32",
    ],
    target_compatible_with = ["@pico-sdk//bazel/constraint:host"],
)

cc_test(
    name = "ethernet_frame_test",
    srcs = ["ethernet_frame_test.cpp"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
        "//src/mac:ethernet_frame",
        "//src/mac:mac_address",
    ],
    target_compatible_with = ["@pico-sdk//bazel/constraint:host"],
)

cc_test(
    name = "frame_builder_test",
    srcs = ["frame_builder_test.cpp"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
        "//src/mac:crc32",
        "//src/mac:ethernet_frame",
        ":frame_builder_by_value",
    ],
    target_compatible_with = ["@pico-sdk//bazel/constraint:host"],
)

cc_test(
    name = "frame_filter_test",
    srcs = ["frame_filter_test.cpp"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
        "//src/mac:frame_filter",
        "//src/mac:mac_address",
    ],
    target_compatible_with = ["@pico-sdk//bazel/constraint:host"],
)
