// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Martino Pilia
//
// These are the descriptor callbacks TinyUSB invokes during enumeration. The
// configuration descriptor is generated by TinyUSB's TUD_CDC_NCM_DESCRIPTOR
// template macro, so the (error-prone) interface/endpoint/functional-descriptor
// layout comes from the maintained stack rather than hand-rolled bytes.

#include <algorithm>
#include <array>
#include <cstddef>
#include <cstdint>
#include <span>
#include <string_view>

#include "tusb.h" // IWYU pragma: keep

#include "src/mac/frame_filter.h"
#include "src/mac/mac_address.h"
#include "src/phy/phy_stats.h"

namespace pico_ethernet {
namespace {

// pid.codes test VID/PID for open-source/hobby projects.
constexpr std::uint16_t USB_VID{0x1209};
constexpr std::uint16_t USB_PID{0x0001};
constexpr std::uint16_t USB_BCD_DEVICE{0x0100};

constexpr std::uint8_t STRID_LANGID{0};
constexpr std::uint8_t STRID_MANUFACTURER{1};
constexpr std::uint8_t STRID_PRODUCT{2};
constexpr std::uint8_t STRID_SERIAL{3};
constexpr std::uint8_t STRID_INTERFACE{4};
constexpr std::uint8_t STRID_MAC{5};

// NCM occupies two interfaces: communication (ITF_NUM_CDC) and data (ITF_NUM_CDC + 1).
constexpr std::uint8_t ITF_NUM_CDC{0};
constexpr std::uint8_t ITF_NUM_TOTAL{2};

// Endpoint addresses. Notification is interrupt IN; data is a bulk IN/OUT pair.
constexpr std::uint8_t EPNUM_NET_NOTIF{0x81};
constexpr std::uint8_t EPNUM_NET_OUT{0x02};
constexpr std::uint8_t EPNUM_NET_IN{0x82};

constexpr std::uint16_t CONFIG_TOTAL_LEN{TUD_CONFIG_DESC_LEN + TUD_CDC_NCM_DESC_LEN};

// NCM notification-endpoint bInterval (ms) and bmNetworkCapabilities. We advertise
// SetEthernetPacketFilter and the 8-byte NtbInputSize negotiation, both handled by
// the TinyUSB NCM driver. Multicast filtering and statistics are advertised
// separately through the Ethernet Networking functional descriptor fields below.
constexpr std::uint8_t NET_NOTIF_INTERVAL_MS{50};
constexpr std::uint8_t NCM_CAPABILITIES{NCM_NETWORK_CAPS_ETH_FILTER | NCM_NETWORK_CAPS_NTB_INPUT_SIZE};

constexpr tusb_desc_device_t DEVICE_DESCRIPTOR{
    .bLength = sizeof(tusb_desc_device_t),
    .bDescriptorType = TUSB_DESC_DEVICE,
    .bcdUSB = 0x0200,
    // Interface Association Descriptor: the NCM control + data interfaces are
    // grouped into one function.
    .bDeviceClass = TUSB_CLASS_MISC,
    .bDeviceSubClass = MISC_SUBCLASS_COMMON,
    .bDeviceProtocol = MISC_PROTOCOL_IAD,
    .bMaxPacketSize0 = CFG_TUD_ENDPOINT0_SIZE,
    .idVendor = USB_VID,
    .idProduct = USB_PID,
    .bcdDevice = USB_BCD_DEVICE,
    .iManufacturer = STRID_MANUFACTURER,
    .iProduct = STRID_PRODUCT,
    .iSerialNumber = STRID_SERIAL,
    .bNumConfigurations = 1,
};

constexpr std::array CONFIGURATION_DESCRIPTOR{std::to_array<std::uint8_t>({
    TUD_CONFIG_DESCRIPTOR(1, ITF_NUM_TOTAL, 0, CONFIG_TOTAL_LEN, 0, 200),
    // itf, description str, MAC str, notif EP + size, data EP out/in + size,
    // max segment size, notification bInterval, NCM capabilities, number of
    // multicast filters we support (wNumberMCFilters), bmEthernetStatistics bitmap
    // (which GetEthernetStatistic counters we answer). D15 (perfect-filtering) is
    // left clear: the value is a plain count, which the host honors by programming
    // the list; our exact matching is a valid refinement.
    TUD_CDC_NCM_DESCRIPTOR(
        ITF_NUM_CDC,
        STRID_INTERFACE,
        STRID_MAC,
        EPNUM_NET_NOTIF,
        64,
        EPNUM_NET_OUT,
        EPNUM_NET_IN,
        CFG_TUD_ENDPOINT0_SIZE,
        CFG_TUD_NET_MTU,
        NET_NOTIF_INTERVAL_MS,
        NCM_CAPABILITIES,
        FrameFilter::MAX_MULTICAST,
        ETHERNET_STATISTICS_BITMAP),
})};
static_assert(CONFIGURATION_DESCRIPTOR.size() == CONFIG_TOTAL_LEN);

// Indexed from STRID_MANUFACTURER.
constexpr std::array<std::string_view, 4> DESCRIPTOR_STRINGS{
    "pico_ethernet",       // STRID_MANUFACTURER
    "Pico 2 Ethernet NIC", // STRID_PRODUCT
    "0001",                // STRID_SERIAL
    "CDC-NCM",             // STRID_INTERFACE
};

std::array<std::uint16_t, 32 + 1> desc_str{};

// Builds string descriptor `index` into desc_str, or returns nullptr for an unknown
// index so TinyUSB stalls the request.
const std::uint16_t* string_descriptor(std::uint8_t index) {
    std::size_t chr_count{0};

    if (index == STRID_LANGID) {
        desc_str[1] = 0x0409; // English (United States)
        chr_count = 1;
    } else if (index == STRID_MAC) {
        const MacAddress mac{std::span<const std::uint8_t, MacAddress::LENGTH>{tud_network_mac_address}};
        for (const char c : mac.to_imac_string()) {
            desc_str[1 + chr_count] = static_cast<std::uint16_t>(c);
            ++chr_count;
        }
    } else {
        const std::size_t string_index{static_cast<std::size_t>(index - STRID_MANUFACTURER)};
        if (string_index >= DESCRIPTOR_STRINGS.size()) {
            return nullptr;
        }
        const std::string_view str{DESCRIPTOR_STRINGS[string_index]};
        chr_count = std::min(str.size(), desc_str.size() - 1);
        for (std::size_t i{0}; i < chr_count; ++i) {
            desc_str[1 + i] = static_cast<std::uint16_t>(str[i]);
        }
    }

    // First 16-bit word: length in bytes (incl. header) and descriptor type.
    desc_str[0] = static_cast<std::uint16_t>((TUSB_DESC_STRING << 8) | (2 * chr_count + 2));
    return desc_str.data();
}

} // namespace
} // namespace pico_ethernet

extern "C" {

const std::uint8_t* tud_descriptor_device_cb(void) {
    return reinterpret_cast<const std::uint8_t*>(&pico_ethernet::DEVICE_DESCRIPTOR);
}

const std::uint8_t* tud_descriptor_configuration_cb(std::uint8_t index) {
    (void)index;
    return pico_ethernet::CONFIGURATION_DESCRIPTOR.data();
}

const std::uint16_t* tud_descriptor_string_cb(std::uint8_t index, std::uint16_t langid) {
    (void)langid;
    return pico_ethernet::string_descriptor(index);
}

} // extern "C"
