// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Martino Pilia
//
// Pico 2 Ethernet NIC - USB descriptors
// Phase 1: CDC-ECM, full speed, single configuration.
//
// These are the descriptor callbacks TinyUSB invokes during enumeration. The
// configuration descriptor is generated by TinyUSB's TUD_CDC_ECM_DESCRIPTOR
// template macro, so the (error-prone) interface/endpoint/functional-descriptor
// layout comes from the maintained stack rather than hand-rolled bytes.

#include <cstddef>
#include <cstdint>
#include <cstring>
#include <span>

#include "tusb.h" // IWYU pragma: keep

#include "src/mac/mac_address.h"

namespace {

// pid.codes test VID/PID for open-source/hobby projects.
constexpr std::uint16_t USB_VID{0x1209};
constexpr std::uint16_t USB_PID{0x0001};
constexpr std::uint16_t USB_BCD_DEVICE{0x0100};

enum {
    STRID_LANGID = 0,
    STRID_MANUFACTURER,
    STRID_PRODUCT,
    STRID_SERIAL,
    STRID_INTERFACE,
    STRID_MAC,
};

enum {
    ITF_NUM_CDC = 0,
    ITF_NUM_CDC_DATA,
    ITF_NUM_TOTAL,
};

// Endpoint addresses. Notification is interrupt IN; data is a bulk IN/OUT pair.
constexpr std::uint8_t EPNUM_NET_NOTIF{0x81};
constexpr std::uint8_t EPNUM_NET_OUT{0x02};
constexpr std::uint8_t EPNUM_NET_IN{0x82};

constexpr std::uint16_t CONFIG_TOTAL_LEN{TUD_CONFIG_DESC_LEN + TUD_CDC_ECM_DESC_LEN};

const tusb_desc_device_t desc_device = {
    .bLength = sizeof(tusb_desc_device_t),
    .bDescriptorType = TUSB_DESC_DEVICE,
    .bcdUSB = 0x0200,
    // Interface Association Descriptor: the ECM control + data interfaces are
    // grouped into one function.
    .bDeviceClass = TUSB_CLASS_MISC,
    .bDeviceSubClass = MISC_SUBCLASS_COMMON,
    .bDeviceProtocol = MISC_PROTOCOL_IAD,
    .bMaxPacketSize0 = CFG_TUD_ENDPOINT0_SIZE,
    .idVendor = USB_VID,
    .idProduct = USB_PID,
    .bcdDevice = USB_BCD_DEVICE,
    .iManufacturer = STRID_MANUFACTURER,
    .iProduct = STRID_PRODUCT,
    .iSerialNumber = STRID_SERIAL,
    .bNumConfigurations = 1,
};

const std::uint8_t desc_fs_configuration[] = {
    TUD_CONFIG_DESCRIPTOR(1, ITF_NUM_TOTAL, 0, CONFIG_TOTAL_LEN, 0, 100),
    // itf, description str, MAC str, notif EP + size, data EP out/in + size, max segment size
    TUD_CDC_ECM_DESCRIPTOR(
        ITF_NUM_CDC,
        STRID_INTERFACE,
        STRID_MAC,
        EPNUM_NET_NOTIF,
        64,
        EPNUM_NET_OUT,
        EPNUM_NET_IN,
        CFG_TUD_ENDPOINT0_SIZE,
        CFG_TUD_NET_MTU),
};

const char* const string_desc_arr[] = {
    "pico_ethernet",       // STRID_MANUFACTURER
    "Pico 2 Ethernet NIC", // STRID_PRODUCT
    "0001",                // STRID_SERIAL
    "CDC-ECM",             // STRID_INTERFACE
};

std::uint16_t desc_str[32 + 1];

} // namespace

extern "C" {

const std::uint8_t* tud_descriptor_device_cb(void) { return reinterpret_cast<const std::uint8_t*>(&desc_device); }

const std::uint8_t* tud_descriptor_configuration_cb(std::uint8_t index) {
    (void)index;
    return desc_fs_configuration;
}

const std::uint16_t* tud_descriptor_string_cb(std::uint8_t index, std::uint16_t langid) {
    (void)langid;
    std::size_t chr_count{0};

    if (index == STRID_LANGID) {
        desc_str[1] = 0x0409; // English (United States)
        chr_count = 1;
    } else if (index == STRID_MAC) {
        const pico_ethernet::MacAddress mac{std::span<const std::uint8_t, pico_ethernet::MacAddress::LENGTH>(
            tud_network_mac_address, pico_ethernet::MacAddress::LENGTH)};
        const auto hex = mac.to_ecm_string();
        for (char c : hex) {
            desc_str[1 + chr_count++] = static_cast<std::uint16_t>(c);
        }
    } else {
        const std::size_t arr_index{static_cast<std::size_t>(index - STRID_MANUFACTURER)};
        if (arr_index >= sizeof(string_desc_arr) / sizeof(string_desc_arr[0])) {
            return nullptr;
        }
        const char* str{string_desc_arr[arr_index]};
        chr_count = std::strlen(str);
        const std::size_t max_count{sizeof(desc_str) / sizeof(desc_str[0]) - 1};
        if (chr_count > max_count) {
            chr_count = max_count;
        }
        for (std::size_t i{0}; i < chr_count; ++i) {
            desc_str[1 + i] = static_cast<std::uint16_t>(str[i]);
        }
    }

    // First 16-bit word: length in bytes (incl. header) and descriptor type.
    desc_str[0] = static_cast<std::uint16_t>((TUSB_DESC_STRING << 8) | (2 * chr_count + 2));
    return desc_str;
}

} // extern "C"
