load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "pico_ethernet_firmware",
    srcs = ["main.cpp"],
    linkopts = ["-Wl,--gc-sections"],
    deps = [
        "//src/mac:mac_address",
        "//src/phy:phy",
        "//src/usb:usb_net_device",
        "//src/usb:usb_descriptors",
        "//src/util:instrumentation",  # TEMPORARY: M1.5 Step 1 diagnostics
        "//src/util:led_heartbeat",
        "@pico-sdk//src/rp2_common/pico_stdlib",
    ],
)
